version: '3.4'

services:
  platformservice:
    image: ${DOCKER_REGISTRY-}platformservice
    build:
      context: .
      dockerfile: src/PlatformService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  commandsservice:
    image: ${DOCKER_REGISTRY-}commandsservice
    build:
      context: .
      dockerfile: src/CommandsService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    depends_on:
      - platformservice

  

